export enum DisputeType {
  TYPO = "TYPO",
  MISSING_CONTENT = "MISSING_CONTENT",
  IMAGE_QUALITY = "IMAGE_QUALITY",
  REISSUE_REQUIRED = "REISSUE_REQUIRED",
  IDENTITY_MISMATCH = "IDENTITY_MISMATCH",
  DOCUMENT_INVALID = "DOCUMENT_INVALID",
  OTHERS = "OTHERS",
}
