import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsString } from 'class-validator';

export class AcceptTestnetCredentialReq {
  @ApiProperty({
    description: 'XRPL signed transaction blob generated by the subject wallet from the prepared CredentialAccept transaction.',
    example: '12002F2280000000240000000168400000000000000C...',
  })
  @IsString()
  @IsNotEmpty()
  readonly signedTransactionBlob!: string;
}
