import { ApiProperty } from "@nestjs/swagger";
import { IsEnum, IsNotEmpty, IsString } from "class-validator";
import { XrplCredentialDeleteSubmitterRole } from "../../../domain/credential/enum/xrpl-credential-delete-submitter-role.enum";

export class DeleteTestnetCredentialReq {
  @ApiProperty({
    enum: XrplCredentialDeleteSubmitterRole,
    description:
      "XLS-70 CredentialDelete submitter. SUBJECT signs as the credential holder, ISSUER signs as the issuer.",
    example: XrplCredentialDeleteSubmitterRole.SUBJECT,
  })
  @IsEnum(XrplCredentialDeleteSubmitterRole)
  readonly submitterRole!: XrplCredentialDeleteSubmitterRole;

  @ApiProperty({
    description:
      "XRPL signed transaction blob generated by the selected submitter wallet from the prepared CredentialDelete transaction.",
    example: "1200302280000000240000000168400000000000000C...",
  })
  @IsString()
  @IsNotEmpty()
  readonly signedTransactionBlob!: string;
}
