export enum CredentialDocumentStageState {
  ISSUED_PENDING_ACCEPT = "ISSUED_PENDING_ACCEPT",
  ISSUED_ACCEPTED = "ISSUED_ACCEPTED",
  EXPIRED = "EXPIRED",
  REVOKED = "REVOKED",
  FAILED = "FAILED",
}
