export enum DocumentStage {
  AUTHORITY_ISSUED = 'AUTHORITY_ISSUED',
  DOCUMENT_ARRIVED = 'DOCUMENT_ARRIVED',
  TRANSLATED_NOTARIZED = 'TRANSLATED_NOTARIZED',
  APOSTILLE_ISSUED = 'APOSTILLE_ISSUED',
  WALLET_STORED = 'WALLET_STORED',
}
