export enum ComplianceReason {
  VISA_EXPIRED = 'VISA_EXPIRED',
  VISA_REVOKED = 'VISA_REVOKED',
  TAX_OVERDUE = 'TAX_OVERDUE',
  VISA_RENEWED = 'VISA_RENEWED',
  MANUAL_OVERRIDE = 'MANUAL_OVERRIDE',
}
